### ISSUE TITLE
Module Not Found error from dependency in requirements.txt

### ISSUE THREAD

**Issue by phil-epl** [GoogleCloudPlatform/functions-framework-python#108]
I am trying to test a function using the functions-framework that has dependencies inside a requirements.txt file but I am getting an error that the module is not found after running the `functions-framework --target=main` command.

![image](https://user-images.githubusercontent.com/67131733/105567063-aa629200-5cfd-11eb-8122-f23661fd6377.png)

** Edit the functions-framework only seems to work when I run `pip install functions-framework` in my virtual env. Why would it not work with a functions-framework installation in my main environment?

**Comment by di** [comment]
Hi @phil-epl, the framework won't handle installing your dependencies for you. You'll need to have both the framework (`pip install functions-framework`) and your functions dependencies (`pip install -r requirements.txt`) installed into whatever environment you're using.

Let me know if you have any other questions!

**Comment by di** [comment]
Closing as there's nothing to do here.
