### ISSUE TITLE
Testing Functions in Google Colab

### ISSUE THREAD

**Issue by dirkbosman** [GoogleCloudPlatform/functions-framework-python#111]
**Use Case:** 
- Test functions in a Google Colab (within Google Drive). 
- Include ```flask-ngrok``` in the requirement.txt already.

This will allow the Flask app (which is running on localhost) to be available temporarily over the Internet via the excellent [ngrok](https://ngrok.com/) tool, when one runs ```main.py``` thereafter:

```python
from flask import Flask
from flask import request
from flask_ngrok import run_with_ngrok
app = Flask(__name__)
run_with_ngrok(app)
@app.route("/")
def root():
    url = request.method
    return "Hello world!"
app.run()
```

Access function(s) by navigating to the following urls:
```
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Running on http://<dynamic-value>.ngrok.io
 * Traffic stats available on http://127.0.0.1:4040
```

**Comment by di** [comment]
Closing per https://github.com/GoogleCloudPlatform/functions-framework-python/pull/110#issuecomment-778429275 but thanks for raising the issue!
