### ISSUE TITLE
Make MAX_CONTENT_LENGTH configurable

### ISSUE THREAD

**Issue by bmritz** [GoogleCloudPlatform/functions-framework-python#113]
We have a use-case that often requires request payloads larger than the current MAX_CONTENT_LENGTH (https://github.com/GoogleCloudPlatform/functions-framework-python/blob/master/src/functions_framework/__init__.py#L41). 

Functions Framework is intended to be run on K8ts or Cloud Run, both of which can be configured to handle larger requests than the current `MAX_CONTENT_LENGTH`, so configuring it to be larger would open up the library for more use cases.

**Comment by di** [comment]
Thanks for the issue @bmritz, I think I agree.

@asriniva, you added this in https://github.com/GoogleCloudPlatform/functions-framework-python/pull/66/, but I'm not sure it's necessary in order to resolve that issue. Was that just to guard against a very large request on GCF? What would be the effect of removing that limit in the runtime? I assume the quota in GCF is already enforced somewhere higher up the stack.

**Comment by asriniva** [comment]
Yeah this is strictly as a guard for GCF, as you say I think the quota would be enforced elsewhere in the stack. I think it can be safely removed.

**Comment by grant** [comment]
Pull requests are welcome. We'd allow it. PR also needs testing.

https://github.com/GoogleCloudPlatform/functions-framework-python/blob/9af6591465ce59516c5a3058906c0685a0dcea01/src/functions_framework/__init__.py#L38

**Comment by t510599** [comment]
Hi @grant, I have implemented this feature and submitted the PR in #196.
Please take a look when you are free, thank you.

**Comment by grant** [comment]
> Hi @grant, I have implemented this feature and submitted the PR in #196.
> Please take a look when you are free, thank you.

Thanks @t510599. I'll defer the PR review to @anniefu.

**Comment by garethgeorge** [comment]
Looks like this was resolved by the PR, marking as closed. Thanks all!

**Comment by grant** [comment]
> Looks like this was resolved by the PR, marking as closed. Thanks all!

The PR was never merged

**Comment by sellpick-rudolf** [comment]
The limit was actually fully removed as of 3.2.1:

https://github.com/GoogleCloudPlatform/functions-framework-python/blob/main/CHANGELOG.md#321-2022-11-09
https://github.com/GoogleCloudPlatform/functions-framework-python/pull/205
