### ISSUE TITLE
Different source than the root directory doesn't seem to work

### ISSUE THREAD

**Issue by matoous** [GoogleCloudPlatform/functions-framework-python#120]
Hi!

Consider following project structure:

```
.
├── README.md
├── src
│  ├── main.py
│  ├── requirements.txt
```

Not sure whether such structure makes sense but currently it works for me with Google Cloud Functions + terraform. `src` directory gets zipped, uploaded to gcs and deployed. Now, I tried to also create an option for easier local development, but:

## Problem

Using different than default `GOOGLE_FUNCTION_SOURCE` doesn't seem to work. Using the `GOOGLE_FUNCTION_SOURCE` with directory path (e.g. `GOOGLE_FUNCTION_SOURCE=src`) fails with:

```
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/bin/functions-framework", line 8, in <module>
    sys.exit(_cli())
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/functions_framework/_cli.py", line 37, in _cli
    app = create_app(target, source, signature_type)
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/functions_framework/__init__.py", line 216, in create_app
    source_module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 553, in module_from_spec
AttributeError: 'NoneType' object has no attribute 'loader'
```

With full path to the file with the function specified (i.e. `GOOGLE_FUNCTION_SOURCE=src/main.py`) functions framework fails to install packages for the function and the function fails on the first import of external package, in my case:

```
ModuleNotFoundError: No module named 'weasyprint'
```

## Solution

Allow users to specify the source directory instead of source file, in fact, I think that's how the Google Cloud Functions handle it: https://cloud.google.com/functions/docs/writing#structuring_source_code

**Comment by di** [comment]
> With full path to the file with the function specified (i.e. `GOOGLE_FUNCTION_SOURCE=src/main.py`) functions framework fails to install packages for the function and the function fails of first import of external package

I'm a little confused here: regardless of your source layout, the framework will not install external packages for you (even if they are specified in `requirements.txt`) as it assumes they have already been installed into the environment.

You should be able to use `--source` and `GOOGLE_FUNCTION_SOURCE` to specify the path to the file in which the function is defined, and that file can import _local_ modules relative to that directory. E.g. from the root of this repo, I can run:

```
$ functions-framework --debug --target function --source tests/test_functions/http_with_import/main.py
 * Serving Flask app "function" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
 * Restarting with fsevents reloader
 * Debugger is active!
 * Debugger PIN: 793-823-273
 ```

**Comment by xSAVIKx** [comment]
I believe the actual request here is to be able to specify not only the function source (main.py), but also the path to the `requirements.txt` in order to be able to support virtually any kind of the source code format. It is a standard situation when requirements are not in the root folder.
