### ISSUE TITLE
Support `click>=7.0<9.0`

### ISSUE THREAD

**Issue by di** [GoogleCloudPlatform/functions-framework-python#127]
We currently depend on `click` but restrict it's major version:

https://github.com/GoogleCloudPlatform/functions-framework-python/blob/3f9e0659e02257098e21e9af62dc4ccf31b05856/setup.py#L53

The `click==8.0.0` release was made yesterday https://pypi.org/project/click/8.0.0/ and a full changelog is here: https://click.palletsprojects.com/en/8.0.x/changes/

This can introduce conflicts with the functions framework if the user has a dependency or subdependency on click, which results in an error at deploy-time like:

```
$ gcloud functions deploy visitme --runtime python38 --trigger-http --allow-unauthenticated
Deploying function (may take a while - up to 2 minutes)...⠹
For Cloud Build Stackdriver Logs, visit: https://console.cloud.google.com/logs/viewer?project=wescpy-ccsc&advancedFilter=resource.type%3Dbuild%0Aresource.labels.build_id%3D84accc73-466c-4dbb-a681-9eb777000e24%0AlogName%3Dprojects%2Fwescpy-ccsc%2Flogs%2Fcloudbuild
Deploying function (may take a while - up to 2 minutes)...failed.
ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Build failed: found incompatible dependencies: "functions-framework 2.1.2 has requirement click<8.0,>=7.0, but you have click 8.0.0."; Error ID: 945b0f01
```

We should make any changes necessary to support `click>=7.0<9.0` and make a new release with this updated version range.

**Comment by raghav-arora-nbs** [comment]
Thanks for this. But what's the workaround for this until we get this fix in any released version @di ?
As this is breaking builds when deploying via gcloud functions deploy on python38.

**Comment by raghavarora12** [comment]
Thanks for this. But what's the workaround for this until we get this fix in any released version @di ? 
As this is breaking builds when deploying via gcloud functions deploy on python38.

**Comment by di** [comment]
Hi @raghavarora12, you shouldn't need to specify `click` or `flask` in your `requirements.txt` file when deploying. Are you able to just remove them entirely?
