### ISSUE TITLE
How to test write to storage bucket as trigger

### ISSUE THREAD

**Issue by dr808** [GoogleCloudPlatform/functions-framework-python#132]
Looking to test locally a write to a storage bucket as trigger. I just need to get the filename `event['name']` to send to transcription.

**Comment by di** [comment]
Hi @dr808, can you give us more details? It sounds like you're trying to test a function locally that writes to a storage bucket? What exactly would you like to test? Can you share your function with us?

**Comment by dr808** [comment]
Sure, use case is pretty simple. Audio file gets written to cloud storage bucket which triggers cloud function to create a task (long running) to transcribe the audio.

I'd like to trigger the function locally on `google.storage.object.finalize`

**Comment by di** [comment]
You can write a unit test for any background function like this:

```python
from functions_framework import create_app

def test_background_function_executes():
    source = TEST_FUNCTIONS_DIR / "background_trigger" / "main.py"
    target = "function"
    background_event_client = create_app(target, source, "event").test_client()

    background_json = {
        "context": {
            "eventId": "some-eventId",
            "timestamp": "some-timestamp",
            "eventType": "some-eventType",
            "resource": "some-resource",
        },
        "data": tempfile_payload,
    }

    resp = background_event_client.post("/", json=background_json)
    assert resp.status_code == 200
```

Here, you determine what the `event` and `context` passed to your function would be, and would mock out the calls to any external services.

Or, if you're just trying to call the function locally, since it's just a Python function, you can write a script like:

```python
from main import your_function
event = ...
context = ...
your_function(event, context)
```

Where `event` and `context` are whatever your function is expecting.

**Comment by dr808** [comment]
Ok, mock data it is. Thanks.
