### ISSUE TITLE
Adding dryrun option

### ISSUE THREAD

**Issue by asriniva** [GoogleCloudPlatform/functions-framework-python#14]
To be able to more easily catch syntax errors and related issues in the function before starting a server, a dryrun would be helpful. The function framework for Node.js has an option for this: https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/118

**Comment by di** [comment]
Released in [`functions-framework==1.1.1`](https://pypi.org/project/functions-framework/1.1.1/).
