### ISSUE TITLE
Support CloudEvent as triggers in Functions Frameworks

### ISSUE THREAD

**Issue by anguillanneuf** [GoogleCloudPlatform/functions-framework-python#141]
See https://github.com/GoogleCloudPlatform/functions-framework-python/issues/23#issuecomment-878138500

@frankie567

**Comment by di** [comment]
If I'm understanding correctly, this is already supported (added in #56) -- or am I missing something?

**Comment by anguillanneuf** [comment]
Ohh, you are right. 

I think the issue should be to update the Pub/Sub quickstart to use `(data, context)`:

https://github.com/GoogleCloudPlatform/functions-framework-python#quickstart-pubsub-emulator

**Comment by di** [comment]
I'll close this and reopen #23.
