### ISSUE TITLE
strict type check doesn't allow for callable objects

### ISSUE THREAD

**Issue by jcjones1515** [GoogleCloudPlatform/functions-framework-python#145]
The [strict type check here](https://github.com/GoogleCloudPlatform/functions-framework-python/blob/master/src/functions_framework/__init__.py#L266-L273), prevents us from using a python object that implements `__call__`.  I would propose (and am happy to contribute a PR for) changing this check to use [`callable(...)`](https://docs.python.org/3/library/functions.html#callable) instead to allow more flexibility in what gets passed in.  I think we'd also have to prevent classes from being passed in, since those would also be "callable".

(this used to work in GCF for us, so I assume that there was a change at some point recently that now prevents this)

If this sounds good, I'll create a quick PR for this change.

Thanks!

**Comment by di** [comment]
That check has been there since the very first commit, so I'm not sure the behavior has changed over time.

I think this would be OK, but could you give us some more detail about why you need this? Any examples would be great as well. Thanks!

**Comment by jcjones1515** [comment]
I'm not sure whats changed, but we've used an internal framework for a few years with GCF.  Starting a week or two ago we started getting caught by this check.

w/o posting the whole code, our framework works something like this:

```
class MyCloudFunction(InternalSDKBaseClass):
    def __init__(*args, **kwargs):
        pass # do some initialization

    def __call__(*args, **kwargs):
        pass # do the work of the function here
```

You can then instantiate it and use that instance as the entry point like:

```
my_entry_point = MyCloudFunction(some_init_parameters)
```

**Comment by di** [comment]
Thanks. I think it will be fine to convert this to a check for `callable`, feel free to make a PR!

Just a follow-up question, as I'm trying to understand the use case here: why do you use this pattern? It seems like it would help ensure that initialization is the same across multiple Cloud Functions, is that the main goal? If you have multiple functions using this, how do you structure your source code? Where do you define `InternalSDKBaseClass`? Where are the functions defined? How do you make updates to `InternalSDKBaseClass` and deploy them across all functions?

**Comment by janell-chen** [comment]
Hello, since there is no further information or PR to check for a callable, I will close this issue for now. Please feel free to reopen if this is still necessary.
