### ISSUE TITLE
CloudEvent signature decorator should be snake case

### ISSUE THREAD

**Issue by matthewrobertson** [GoogleCloudPlatform/functions-framework-python#166]
"Cloud Event" is two words so the decorator should be snake case:

```python
import functions_framework

@functions_framework.cloud_event
def hello_cloud_event(cloud_event):
  pass
```

**Comment by grant** [comment]
Note: I believe we should still refer to these events as `CloudEvent`, but the appropriate snake case for this should be `cloud_event` as mentioned above.
