### ISSUE TITLE
How to log information in the function

### ISSUE THREAD

**Issue by lizzzcai** [GoogleCloudPlatform/functions-framework-python#172]
For a function, can I define my log format and log the information I needed?

I tried the following but it is not working. No log is showing in the console.

```
import logging

logging.basicConfig(format='%(levelname)s:%(message)s', level=logging.DEBUG)
logging.debug('This message should appear on the console')

def hello(request):
    logging.debug('Hello world')
    return "Hello world!"
```

**Comment by grant** [comment]
Hi there,

Here are the docs for writing logs:
https://cloud.google.com/functions/docs/monitoring/logging

You can also use the Cloud Logging client library to log with detailed information:
https://cloud.google.com/logging/docs/reference/libraries

I would also ensure your logs are within the function. Hope this helps.

**Comment by shukryzablah** [comment]
I have several usages of the `logging` library. @grant Does your comment imply that I _have_ to use google cloud logging for the local console to show my logs? 

If no, how can I make sure that normal `logging` usage shows up in the development console?

**Comment by grant** [comment]
Sorry @shukryzablah, I don't work at Google anymore. I'd ask someone else like @anniefu or open a new issue – although I think the docs answer your question.
