### ISSUE TITLE
make host configurable

### ISSUE THREAD

**Issue by kanekv** [GoogleCloudPlatform/functions-framework-python#19]
On mac every time it reloads there is a firewall alert because it's fixed listen on `0.0.0.0`. Can we add `--host` option to override the interface?

**Comment by di** [comment]
Yup, sounds like a good idea. Would you like to work on this?

**Comment by kanekv** [comment]
Sure, I'll submit a PR if you are not against it.

**Comment by di** [comment]
Please do!

**Comment by di** [comment]
Released in [`functions-framework==1.2.0`](https://pypi.org/project/functions-framework/1.2.0/).
