### ISSUE TITLE
Untyped functions_framework.http

### ISSUE THREAD

**Issue by racinmat** [GoogleCloudPlatform/functions-framework-python#190]
The decorator `functions_framework.http` is untyped, leading to `Untyped decorator makes function "main" untyped` errors when using mypy. 
Would it be possible to add mypy typing? Thanks.

**Comment by grant** [comment]
Sounds reasonable.

https://github.com/GoogleCloudPlatform/functions-framework-python/blob/f2285f96072d7ab8f00ada0d5f8c075e2b4ad364/src/functions_framework/__init__.py#L72

I attempted to add more types here:

https://github.com/GoogleCloudPlatform/functions-framework-python/pull/191

**Comment by christippett** [comment]
I wrote the snippet below for another project. It's pulling in the same types used by Flask, so things like the request object and expected return type for function handlers are all properly annotated and play nice with intellisense.

Given Flask is already included as a dependency in the functions framework, it might be worth piggybacking on the types defined in [`flask.typing`](https://github.com/pallets/flask/blob/main/src/flask/typing.py) 

```python
from flask.typing import RouteCallable

def http(func: RouteCallable) -> RouteCallable:
    """Decorator that registers http as user function signature type."""
    ...

```
