### ISSUE TITLE
Add Cache Control Header to cache responses with Firebase Hosting ?

### ISSUE THREAD

**Issue by ABDERRAHMANE-OUALI** [GoogleCloudPlatform/functions-framework-python#198]
is it possible to add cache control to the response ?

**Comment by josephlewis42** [comment]
Hi @ABDERRAHMANE-OUALI, can you add some additional details about what you've tried so far, what you expected to happen, and what happened instead?

Thanks!

**Comment by josephlewis42** [comment]
We're closing this issue for now because we're waiting on follow-up. Please re-open it if you still need help!
