### ISSUE TITLE
Docs: Missing multiple URL path example

### ISSUE THREAD

**Issue by SrChach** [GoogleCloudPlatform/functions-framework-python#200]
There're no examples on the docs or readme on how to use Functions Framework with multiple http endpoints.

Although it's easy, is not that easy to figure without a real applied example.

Thanks!

**Comment by jama22** [comment]
@SrChach Out of curiosity did do something along the lines of this blog post? https://medium.com/google-cloud/use-multiple-paths-in-cloud-functions-python-and-flask-fc6780e560d3
