### ISSUE TITLE
Not able to run locally

### ISSUE THREAD

**Issue by salmanpary** [GoogleCloudPlatform/functions-framework-python#220]
functions-framework : The term 'functions-framework' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ functions-framework --target=get_topics
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (functions-framework:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

I have tried uninstalling and installing functions-framework
I'm using windows11 and using vscode

**Comment by josephlewis42** [comment]
Hi @salmanpary, this sounds like it might be an issue with your machine's PATH variable. From my understanding Python usually adds to it so pip packages are available, but in some cases may not. I think this guide should help you: https://stackoverflow.com/a/36160069

I'm closing for now, but feel free to re-open if you have additional questions!
