### ISSUE TITLE
Code behaves differently with debug flag

### ISSUE THREAD

**Issue by raghuveer-s** [GoogleCloudPlatform/functions-framework-python#240]
My code has in it, a call to BigQuery using the google python APIs. I am creating a BigQuery client but when calling the query method (https://cloud.google.com/python/docs/reference/bigquery/latest/google.cloud.bigquery.client.Client#google_cloud_bigquery_client_Client_query) on the client, it fails without the debug flag. 

When testing locally with curl, it returns "Empty reply from server". But the same code works with the debug flag. I'm not able to understand what can cause the behavior to change, any help on this would be awesome.

**Comment by janell-chen** [comment]
Do you mind sharing your function? I was able to test locally with curl calling the BigQuery client API in python both with and without the debug flag

**Comment by janell-chen** [comment]
Closing the issue, please feel free to reopen if the issue persists!
