### ISSUE TITLE
Exception has occurred: SystemExit 3

### ISSUE THREAD

**Issue by filipre** [GoogleCloudPlatform/functions-framework-python#253]
Hi!

Sometimes (see below), I get the following exception when I run the functions framework in the VS Code debugger after detecting a code change.

Uncaught Exception
```
Exception has occurred: SystemExit
3
  File "/Users/rene/.vscode/extensions/ms-python.python-2023.9.11461009/pythonFiles/lib/python/debugpy/server/cli.py", line 314, in run_module
    run_module_as_main(options.target, alter_argv=True)
  File "/Users/rene/.vscode/extensions/ms-python.python-2023.9.11461009/pythonFiles/lib/python/debugpy/server/cli.py", line 429, in main
    log.reraise_exception(
  File "/Users/rene/.vscode/extensions/ms-python.python-2023.9.11461009/pythonFiles/lib/python/debugpy/server/cli.py", line 429, in main
    log.reraise_exception(
  File "/Users/rene/.vscode/extensions/ms-python.python-2023.9.11461009/pythonFiles/lib/python/debugpy/__main__.py", line 39, in <module>
    cli.main()
SystemExit: 3
```

The exception is only thrown "sometimes" but when it's thrown, it happens multiple times in a row for each "change" or whenever I save a file. I do not see a pattern when it is thrown and when not. Do you have an idea where this could be coming from and why it only happens sometimes? I first thought it is related to broken code, but that does not seem to be the case.

VS Code Terminal
```
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
 * Serving Flask app '********'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8082
 * Running on http://***.***.***.***:8082
Press CTRL+C to quit
 * Restarting with watchdog (fsevents)
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
 * Debugger is active!
 * Debugger PIN: ***-***-***
 * Detected change in '/Users/rene/Development/*****.py', reloading
```

`launch.json` file:
```json
{
    "name": "▶ Service",
    "type": "python",
    "request": "launch",
    "module": "functions_framework",
    "args": ["--target",  "service", "--debug", "--port=8082"],
    "cwd": "${workspaceFolder}"
}, 
```

Version
```
functions-framework==3.3.0
```

```
$ python -V
Python 3.11.2
```

I'm happy about any pointer to the right direction!

**Comment by KaylaNguyen** [comment]
Hi @filipre, this seems to be a VS Code issue: https://stackoverflow.com/q/52372810. It's not related to #213.
Can you try the workaround suggested and see if that works for you?

**Comment by filipre** [comment]
Thank you for your reply. The Stackoverflow thread shifts the question to "Why does the CLI debugger finishes with the exit code 3"? VS Code will always throw an exception, when python finishes with an error code. I think that's the correct behavior. For example, this code should not throw an exception
```python
sys_exit(0)
```
But this one should
```python
sys_exit(1)
```
I could disable "Uncaught Exceptions" but I do not want this because I would also ignore exceptions in my program code.

The exact line that causes the system exit `3` is
```python
run_module_as_main(options.target, alter_argv=True)
```
and options.target is `'functions_framework'`. The method is defined (?) in [runpy](https://docs.python.org/3/library/runpy.html#module-runpy) somewhere. The `sys.path` looks correct, too and refers to the right virtual env packages and custom packages.

Is there something else I could provide to figure out the root of the problem?

**Comment by filipre** [comment]
Okay I understand now whats happening. I think `run_module_as_main ` **always** exits with error code `3`. I guess sometimes the Debugger was set up to listen only for "Uncaught Exceptions" resulting in the exception and sometimes only to listen for "User Uncaught Exceptions" ignoring the issue. That's why it felt random to me. Unchecking "Uncaught Exceptions" is not a problem anymore because it will still listen for *my* exceptions I think?

Maybe after changing a file, `system_frameworks` does not "properly" stop the debugger and causes the exit code?

**Comment by fswair** [comment]
this error all about library's trigger method.

there is a default "trigger_reload" method and it raises SystemExit when file has been changed.

`def trigger_reload(self, filename: str) -> None:
        self.log_reload(filename)
        sys.exit(3) # just make it disable`

**Comment by filipre** [comment]
>this error all about library's trigger method.

Which library do you mean? functions-framework or something else?

**Comment by quroom** [comment]
To avoid this issue, if you are using django or some framework which makes sys.exit(3) when your code reloded, you can just set "django": true, in your launch.json like htis
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Python Debugger: Remote Attach",
      "type": "debugpy",
      "request": "attach",
      "django": true,
      "connect": {
        "host": "localhost",
        "port": 5678
      },
      "pathMappings": [
        {
          "localRoot": "${workspaceFolder}",
          "remoteRoot": "/app"
        }
      ]
    }
  ]
}
```

**Comment by filipre** [comment]
Thank you so much @quroom, it seems like this solves the issue. It seems more like a hack though since my code has nothing to do with Django. In any case, it seems more related to VSCode then so I will close the issue. Thanks everyone!

**Comment by quroom** [comment]
> Thank you so much @quroom, this solves the issue. It seems more like a hack though since my code has nothing to do with Django. In any case, its more related to VSCode so I will close the issue. Thanks everyone!

That's right maybe there is some code making not to catch Exit code 3 in vscode
