### ISSUE TITLE
Adjust path handling for robots.txt and favicon.ico

### ISSUE THREAD

**Issue by asriniva** [GoogleCloudPlatform/functions-framework-python#27]
Functions frameworks should listen on all paths and forward without modification except /robots.txt and /favicon.ico

This change was added in the nodejs functions framework here: https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/121/

**Comment by di** [comment]
Released in [`functions-framework==1.3.0`](https://pypi.org/project/functions-framework/1.3.0/).
