### ISSUE TITLE
Gunicorn 21 is out

### ISSUE THREAD

**Issue by xSAVIKx** [GoogleCloudPlatform/functions-framework-python#270]
The https://github.com/GoogleCloudPlatform/functions-framework-python/blob/main/setup.py#L57 specify a hard requirement for `gunicorn<21`, is there any particular reason for this? The v21 brings a lot of [fixes](https://github.com/benoitc/gunicorn/releases/tag/21.0.1) as well as official Python3.11 support that were hanging in there in the master branch for years. It'd be great to unblock and let us use the latest gunicorn

**Comment by xSAVIKx** [comment]
any updates&

**Comment by HKWinterhalter** [comment]
Done - https://github.com/GoogleCloudPlatform/functions-framework-python/pull/276

**Comment by xSAVIKx** [comment]
@HKWinterhalter, do you maybe know when this can be released?
