### ISSUE TITLE
Deployment failure: Function failed on loading user code. Error message: File main.py is expected to contain a function named cleanEdges

### ISSUE THREAD

**Issue by AlbertoMQ** [GoogleCloudPlatform/functions-framework-python#28]
Getting the error in title despite being able to see my code in the google cloud platform cloud functions console with the named function.

```
import cloudstorage as gcs
# from google.cloud import storage
import open3d 
import networkx as nx
import numpy as np

client = gcs.Client()
RETURN_BUCKET = 'outgoing_meshtools'

def cleanEdges(data, context):
    ***content of function

**other functions
```

Trigger: Cloud Storage
Event Type: Finalize/Create

**Comment by di** [comment]
Hi @AlbertoMQ, thanks for the report. Can you give us some more context? How are you invoking the functions framework, or where are you running it?
