### ISSUE TITLE
Add Flask 3 support

### ISSUE THREAD

**Issue by xSAVIKx** [GoogleCloudPlatform/functions-framework-python#283]
Flask 3.0 is out for ~2 weeks now. It would be great to add Flask 3 support to the library.

The changelog is available here: https://github.com/pallets/flask/blob/main/CHANGES.rst

**Comment by HKWinterhalter** [comment]
Thank you for the request, I will see when this upgrade can be included.

**Comment by HKWinterhalter** [comment]
FF Python [v3.5](https://github.com/GoogleCloudPlatform/functions-framework-python/releases/tag/v3.5.0) has been released, which allows Flask >= 3.0 to be used.
