### ISSUE TITLE
Make it easier to debug functions in IDEs

### ISSUE THREAD

**Issue by yuri-sergiichuk** [GoogleCloudPlatform/functions-framework-python#29]
Currently, it is super hard to configure the local debug of the functions in PyCharm, moreover, I found it impossible without hacking the `cli.py`.

Here is a way to do it in PyCharm now:
1. Add main function to the `cli.py`:
    ```python
    if __name__ == '__main__':
        cli(sys.argv[1:])
    ```
1. Create PyCharm Python config and choose `functions_framework\cli.py` as a script.
1. Pass required params as `Parameters` in the configuration, e.g. `--port 8088 --signature-type http`, etc.
1. Make sure to set the working directory to the project root (so that the functions framework is able to load the entry point function).
1. Run the created configurations and use PyCharm debugger.

What we can to make life easier:
1. Create `__main__.py` in the functions_framework module and allow running the module as the CLI. Or, add the main function to the `cli.py` itself, maybe worth having both.
2. Create well-structured documentation about debugging functions locally with popular IDEs (PyCharm, VSCode, others?)

**Comment by di** [comment]
Thanks for the report!

I'm not that familiar with PyCharm so bear with me: is it not possible to use a command like `functions-framework --debug --port 8088 --signature-type http`? It has to be some importable Python script?

I think it would be reasonable to add a `__main__.py` and support `python -m functions_framework`, just want to make sure I understand the issue here.

**Comment by yuri-sergiichuk** [comment]
PyCharm has its own debugger that is injected as a sidecar to the module being run with lots of cool functions.

The `--debug` here enabled Flask's debug mode and Flask has its own debugger. I have not found a way to make them work together. That's why I need a way to run the `functions_framework` either as a module or as a script so that PyCharm can do its debug-related magic.

**Comment by di** [comment]
Hi @yuri-sergiichuk, can you try this branch and let me know if it works for you?

You should be able to install it with:

```
pip install git+https://github.com/googlecloudplatform/functions-framework-python.git@add-main
```

**Comment by yuri-sergiichuk** [comment]
Hi @di. Yes, I can run it as a module now and for PyCharm that should be enough.

Also, maybe it still worth having the `__main__` in the `cli.py`? I'm not sure how debuggers work in other IDEs, but right now I still cannot run the `cli.py` directly.

**Comment by di** [comment]
Great!

> Also, maybe it still worth having the `__main__` in the `cli.py`? I'm not sure how debuggers work in other IDEs, but right now I still cannot run the `cli.py` directly.

This particular file is not meant to be run directly. I renamed it `_cli` in #31 to make this more clear.

**Comment by di** [comment]
Released in [`functions-framework==1.3.0`](https://pypi.org/project/functions-framework/1.3.0/).

**Comment by yiga2** [comment]
> Hi @di. Yes, I can run it as a module now and for PyCharm that it enough.

@yuri-sergiichuk can you share what you did in Pycharm to make it run in debug i.e. stop at breakpoints ?

**Comment by yiga2** [comment]
nvm - found it:
![image](https://user-images.githubusercontent.com/25224265/84167222-f0efce80-aa43-11ea-89c8-9cdde7d0e54f.png)

**Comment by dibusan** [comment]
I 

> nvm - found it: ![image](https://user-images.githubusercontent.com/25224265/84167222-f0efce80-aa43-11ea-89c8-9cdde7d0e54f.png)

I got it running, but breakpoints are not stopping. Any ideas ?

**Comment by dibusan** [comment]
> 

Update: removing `--debug` fixed it. It now stops at breakpoints.

**Comment by AnkitKundariya** [comment]
@dibusan 

I have copied  _cli.py from function-framework source code to my GCP Function root dir next to main.py and I'm trying to debug it as shown below but somehow it's not working what's the missing piece here?

```
/Projects/gcpenv/bin/python /home/trick/software/pycharm-professional-2020.3.4/pycharm-2020.3.4/plugins/python/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 32899 --file /home/trick/Downloads/gcpFunction/_cli.py --target helloGcp
Connected to pydev debugger (build 212.5457.59)

Process finished with exit code 0

```

Thanks in advance.
