### ISSUE TITLE
Memory leaks?

### ISSUE THREAD

**Issue by jgrn307** [GoogleCloudPlatform/functions-framework-python#312]
I know this is a big topic and hard to identify the root causes, but I've been banging my head for a bit on this.  I'm running a python function via functions framework and deploying to Cloud Run.  I'm noticing evidence of a memory leak -- each message sent that is processed seems to suck up another 10-20Mb RAM (which, over time, is causing the cloud run containers to fail with out-of-memory).  When I do a local Docker test I'm seeing the same thing -- memory spikes after a run and does not settle back down.  I'm confident I've cleared out any "temp" files, run gc.collect() a lot within the python script (including right before the final return 200).  But I'm seeing the functions-frame (monitored using "top" while shelled into a running container) has a net increase in RAM usage after every message sent.  

Is there any logging or any other sort of temporary files being created by functions-framework that could cause this?  I'm not doing this in --debug mode, this is in production mode.

**Comment by jrmfg** [comment]
Hi - is this still an issue?  If it is, it'd help if you can share some code or details so I can help dig into it.  I'm not aware of any memory leak in ff-python.

**Comment by jrmfg** [comment]
Closing this for now, if you reach out with some details I'll give it a closer look.
