### ISSUE TITLE
Sudden increase in memory usage from 3.5.0 to 3.6.0

### ISSUE THREAD

**Issue by stelsemeyer** [GoogleCloudPlatform/functions-framework-python#323]
Hi everyone,

I noticed quite drastic increases in memory consumption (from 125 to 200-250+ MB) when moving from `3.5.0` to `3.6.0` (we've essentially just pinned `3.x`), without changing any code on my end, running basic python 3.10.

The memory issue was fixed by deploying again with `functions-framework==3.5.0`:

<img width="739" alt="image" src="https://github.com/GoogleCloudPlatform/functions-framework-python/assets/18263836/9156acfc-f6dc-4f26-ae2d-82be6b0f9e81">
(Deployed 3.6.0 yesterday around 15:00, then deployed 3.5.0 again just now, at 11:00, bringing memory back to stable baseline.)

By inspecting the different revision images I noted that two more packages have changed, rest seemed identical:
```
grpcio 1.62.2 to 1.63.0
google-api-core 2.18.0 to 2.19.0
functions-framework 3.5.0 to 3.6.0
```

For reference: I also submitted a Google support case (#50978600) through a business account.

Thanks for checking,
Seb

**Comment by ryantang30** [comment]
@stelsemeyer thank you for opening this issue. I was going mad after deploying a new revision with minor code changes and suddenly encountering a ton of "_Memory limit of 244 MiB exceeded with 285 MiB used. Consider increasing the memory limit, see ..."_ errors. 

As is in your case, we were also pinned to `3.X`, which I believe is what most people will leave as given Cloud Functions docs examples uses `functions-framework==3.*` in `requirements.txt`

After pinning to `functions-framework==3.5.0`, our memory issue went away as well:

![image](https://github.com/GoogleCloudPlatform/functions-framework-python/assets/25238151/a109fa4d-51e7-4d81-80a2-28100b46b5e5)

**Comment by mariojonke** [comment]
The increased memory usage seems to be caused by a change to the gunicorn default configuration which now starts multiple workers instead of previously just one.
The change introducing the problems appears to be this line: https://github.com/GoogleCloudPlatform/functions-framework-python/pull/309/files#diff-cfd2d0a878597880a787937adcf089da516b44b209145ab42515243ac46f7bdeR24
It looks like default values for number of workers and threads were mixed up.

With setting the environment variable `WORKERS` to `1` the memory usage decreases to previous levels:
![image](https://github.com/GoogleCloudPlatform/functions-framework-python/assets/53077411/a81753ba-7357-4c97-bf0c-e94ed4965db6)

**Comment by HKWinterhalter** [comment]
Thank you for raising this issue.

If you encounter this, please pin to `functions-framework==3.5.0` or override the the `WORKERS` and `THREADS` with environment variables to a preferred setting.

We will investigate further.

**Comment by HKWinterhalter** [comment]
We have yanked this version, 3.6.0, from PyPi while we continue to investigate. You can also re-deploy to get back to the previous behavior.

**Comment by stelsemeyer-m60** [comment]
> Hey folks, sorry for the inconvenience this may have caused. A couple of follow up questions that will help us investigate:
> 
> * were you using gen1 or gen2 functions?
> * if you were using gen2 functions, did you have [concurrency](https://cloud.google.com/functions/docs/configuring/concurrency) enabled?
> * were your workloads actually running out of memory or did you just notice and increase in metrics?

Thanks for checking!

- gen2
- no concurrency
- hard to tell, my deployment was only to our staging environment. We use cloud functions to ingest data to BigQuery, I noticed some ingestion delays at that time, so I'd assume it was an actual memory issue

**Comment by stelsemeyer** [comment]
> Hey folks, sorry for the inconvenience this may have caused. A couple of follow up questions that will help us investigate:
> 
> * were you using gen1 or gen2 functions?
> * if you were using gen2 functions, did you have [concurrency](https://cloud.google.com/functions/docs/configuring/concurrency) enabled?
> * were your workloads actually running out of memory or did you just notice and increase in metrics?

Thanks for checking!

- gen2
- no concurrency
- hard to tell, my deployment was only to our staging environment. We use cloud functions to ingest data to BigQuery, I noticed some ingestion delays at that time, so I'd assume it was an actual memory issue

**Comment by mariojonke** [comment]
> Hey folks, sorry for the inconvenience this may have caused. A couple of follow up questions that will help us investigate:
> 
>     * were you using gen1 or gen2 functions?
> 
>     * if you were using gen2 functions, did you have [concurrency](https://cloud.google.com/functions/docs/configuring/concurrency) enabled?
> 
>     * were your workloads actually running out of memory or did you just notice and increase in metrics?

We are using a mixed set of gen1 and gen2 functions and an increase in consumed memory could be observed on both. gen2 functions using the default concurrency setting, so no concurrency actually. 
Functions are set up with an allocated memory of 256MB and the logs were constantly showing ` Memory limit of 256 MiB exceeded with 262 MiB used. Consider increasing...` messages after each invocation. We have log messages that are emitted when the function module is imported, so these should only be logged once per function instance (unless the module gets reloaded). When running into the memory limit these messages were logged right after the next invocation, so it doesn't appear to  be just metrics but actually running into the memory limit.


As a side note, according to the logs the memory limit for gen2 functions doesn't seem to match with the configured allocated memory. E.g. for a function with 256MB of allocated memory the logs showed a slightly lower value:  `Memory limit of 244 MiB exceeded with 327 MiB used`. Not sure if it is just a display issue or the memory actually being lower. 
(Also memory consumption in gen2 generally seems to be a bit higher compared to gen1 but this is OK i guess).

**Comment by Tom3652** [comment]
I have reverted to 3.5.0 because 3.6.0 is not usable unfortunately, even if i set more memory it will consume it all and go in timeout so it's not a solution.
I am using only gen1 functions.

**Comment by jrmfg** [comment]
Thanks for chiming in, all.

We were looking for a way to smooth over a functionality gap between Cloud Functions 1st gen and Cloud Functions 2nd gen (and Cloud Run) by enforcing timeouts after requests time out.  We missed the mark; OOMing existing workloads isn't appropriate for default behavior on a minor release.  Sorry about that.

To move forward, by default, the change will be reverted, and the ability to simulate Cloud Functions 1st gen behavior will be opt-in from the 3.7 release onwards.  We'll look for a way to incorporate this behavior as a default in a future release (maybe 4.0?), but we'll tread lightly here.

**Comment by jrmfg** [comment]
Thanks for the patience - 3.7.0 was just cut and should land in pypi shortly.  If you see any issues, cut an issue here and we'll check it out.
