### ISSUE TITLE
Not able to deploy function with .zip archive

### ISSUE THREAD

**Issue by yuri-sergiichuk** [GoogleCloudPlatform/functions-framework-python#35]
I do understand that the issue is not related to the `functions-framework` directly, but maybe someone from the team can reach the GCF team and ask them to check it out.

So, the issue is the following. I'm not able to deploy a GCF source as `.zip` archive via Cloud Console UI or using terraform. But if I unpack the function and go with `gcloud functions deploy` it works just fine. Here is the error message I got both from Cloud Console UI and from terraform:
```
Error: Error waiting for Creating CloudFunctions Function: Error code 3, message: Build failed: {"cacheStats": [{"status": "MISS", "hash": "8e51312351ee02e20ebdcdcefb100908ee770a1c81810601ddfcd599221c617b", "type": "docker_layer_cac
he", "level": "global"}, {"status": "MISS", "hash": "8e51312351ee02e20ebdcdcefb100908ee770a1c81810601ddfcd599221c617b", "type": "docker_layer_cache", "level": "project"}]}
```

Does anyone have some ideas about what could be wrong? Unfortunately, I cannot share to source code as it is under the NDA. I'll try to create a reproducible example and share it.
Meanwhile, I have also created [issue](https://issuetracker.google.com/issues/154646028) in the public tracker.

**Comment by di** [comment]
Hi @yuri-sergiichuk, the public tracker is the right place for this issue. I'll make sure the team sees it.
