### ISSUE TITLE
Unable to disable debugger when gunicorn is not available

### ISSUE THREAD

**Issue by di** [GoogleCloudPlatform/functions-framework-python#44]
As a problem: Even now I am unable to disable the debugger --debugger False does not work, and it seems to be active per default.

_Originally posted by @ChristianSauer in https://github.com/GoogleCloudPlatform/functions-framework-python/issues/32#issuecomment-627259026_

**Comment by di** [comment]
@ChristianSauer I think I resolved your issue in the latest release, please take a look and let me know.

**Comment by ChristianSauer** [comment]
@di Thanks! Upaded today and the server no longer starts in debug mode.
Sorry for the late answer, really life is crazy busy with kids atm.
