### ISSUE TITLE
HTTP Functions: Global Exception Handler

### ISSUE THREAD

**Issue by ChristianSauer** [GoogleCloudPlatform/functions-framework-python#48]
Is it possible to hook up Flasks global exception handler? Wrapping the whole function into a try..catch feels gross.

**Comment by di** [comment]
There's some additional discussion about this here: https://github.com/GoogleCloudPlatform/functions-framework/issues/18

**Comment by ChristianSauer** [comment]
I have answered in that thread, so maybe we can close this?
