### ISSUE TITLE
Run function in debug mode

### ISSUE THREAD

**Issue by maikelrobier** [GoogleCloudPlatform/functions-framework-python#5]
Is it possible to run the flask server in debug mode?

Let's say I need to debug the function code using the framework from VSCode for example, is there a way to do that currently?

**Comment by di** [comment]
Yes, you can use the `--debug TRUE` command line flag or set the `DEBUG` environment variable to `TRUE`.

**Comment by di** [comment]
FYI, once #15 is released, this will just be a flag (`--debug`) instead of an option (`--debug TRUE`).
