### ISSUE TITLE
Support Signature Type: CloudEvent

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/functions-framework-python#55]
# Support signature type `cloudevent`

This signature type should support HTTP requests with CloudEvent objects delivered via either structured and binary CloudEvent objects. Usually a CloudEvents SDK can handle transforming the HTTP request to a language-native CloudEvent object.

[New signature `cloudevent` in **Functions Framework contract**](https://github.com/GoogleCloudPlatform/functions-framework#cloudevents-functions-signature-type-cloudevent)

The end-user should see the parameter `cloudevent`, which is a native CloudEvent object using the CloudEvent SDK if possible.

## Example User Experience (in Node)

```js
function handler(cloudevent) {
  console.log(cloudevent.id);
  console.log(cloudevent.data.message);
  console.log(cloudevent.custom_values_should_be_accepted);
  return "anything"
}
```

## Example HTTP requests

The CloudEvents specification requires support for both "binary" and "structured" encodings for CloudEvents delivered via HTTP. The Function Framework must support both encodings. A CloudEvents SDK might make this easier, but most SDKs are not complete, so logic may exist within the Framework.

Examples:

### Binary content mode

```json
POST /any/url/is/accepted HTTP/1.1
Host: example.com
ce-specversion: 1.0
ce-type: com.example.someevent
ce-time: 2018-04-05T03:56:24Z
ce-id: 1234-1234-1234
ce-source: /mycontext/subcontext
x-google-custom-header: 77
Content-Type: <contentType>
Content-Length: 33
{
    "message": "Hello World!"
}
```

### Structured content mode

```json
POST /someresource HTTP/1.1
Host: example.com
Content-Type: <contentType>
Content-Length: 266
{
    "specversion": "1.0",
    "type": "com.example.someevent",
    "time": "2018-04-05T03:56:24Z",
    "id": "1234-1234-1234",
    "source": "/mycontext/subcontext",
    "datacontenttype": "application/json",
    "data": {
        "message": "Hello World!"
    },
    "custom_values_should_be_accepted": 42
}
```

A user should be able to access all of the HTTP headers.
A user should be able to access the body of the CloudEvent in the `data` field of an object.

---

- Example PRs:
  - [Node](https://github.com/GoogleCloudPlatform/functions-framework-nodejs/pull/147)
  - [Go](https://github.com/GoogleCloudPlatform/functions-framework-go/pull/29)
  - [.NET](https://github.com/GoogleCloudPlatform/functions-framework-dotnet/pull/66)

**Comment by grant** [comment]
Sometimes GitHub prevents assignment, I think for new users, maybe a comment tag would work? @joelgerard

**Comment by joelgerard** [comment]
OK. I have a PR coming for #55.

**Comment by grant** [comment]
Fixed with #56.

**Comment by grant** [comment]
Re-opening as CE support was reverted.

**Comment by di** [comment]
Cloud Event support is part of the [`version-2.x-dev`](https://github.com/GoogleCloudPlatform/functions-framework-python/tree/version-2.x-dev) branch and was released in [`functions-framework==2.0.0`](https://pypi.org/project/functions-framework/2.0.0/).

**Comment by grant** [comment]
OK. We should still have the landing page/default branch for this repo to be correct.

`def hello(data, context):` for a CloudEvents as stated is not correct.

**Comment by di** [comment]
Done, we now have:
* https://github.com/GoogleCloudPlatform/functions-framework-python/tree/version-1.x-dev -> the v 1.x branch
* https://github.com/GoogleCloudPlatform/functions-framework-python/tree/master -> the 2.x branch

**Comment by grant** [comment]
Cool thanks! 👍
