### ISSUE TITLE
Missing cloud event adapter tests

### ISSUE THREAD

**Issue by joelgerard** [GoogleCloudPlatform/functions-framework-python#57]
We need a complete set of Event adapter tests to ensure that the various combinations of event types (Cloud Event, Binary Cloud Event, Legacy Event) against the different signature types (FUNCTION_SIGNATURE_TYPE=[cloudevent,event]) work.

Don't ship CEs without this in order to ensure backwards compatibility.

**Comment by grant** [comment]
Hi @juliehockett, @di,
It looks like this framework supports CloudEvents on GitHub but it's not published? Do we need to change something before publishing? Maybe you have context on this bug.

(Context: Looking over all the FFs)
