### ISSUE TITLE
Document incoming request type and/or add request parsing examples

### ISSUE THREAD

**Issue by anniefu** [GoogleCloudPlatform/functions-framework-python#80]
Please document the incoming "request" object to the function stub. It is important in the weakly typed languages.

For python, it happens to be a [Flask request](https://flask.palletsprojects.com/en/1.1.x/api/#incoming-request-data), which means I have to call `request.get_json()` to get the request body of POSTs. 

But it could also have feasibly been some alternative like [Django HttpRequest](https://docs.djangoproject.com/en/3.1/ref/request-response/#django.http.HttpRequest), which means I use `request.body` to get the request body of POSTs.

It would also be nice to have an example that parses a request body and/or request URL parameters and provides an example cURL request instead of just returning a string.

**Comment by anniefu** [comment]
@grant

**Comment by di** [comment]
This is documented here: https://cloud.google.com/functions/docs/concepts/events-triggers#functions_parameters-python

There is also a sample of using this in a more complex way here: https://cloud.google.com/functions/docs/calling/http#functions-calling-http-python

Do we need to document it in the framework as well? Could we just link to the Cloud Functions docs instead?

**Comment by grant** [comment]
I believe we should document (mention/add a link) for the incoming request object in this GitHub repo. On the Cloud docs is great as well.

We can use this framework with localhost, Cloud Run, other Clouds etc.
