### ISSUE TITLE
Thread safe feature in macOS > Sierra breaks default behavior. Make worker sync

### ISSUE THREAD

**Issue by dinigo** [GoogleCloudPlatform/functions-framework-python#97]
I'm trying to run my integration tests as stated by the [GCP guide to perform integration tests in cloud functions](https://cloud.google.com/functions/docs/testing/test-http#integration_tests)

However I find an error in macOS where I have to disable the "safe thread" option so that gunicorn can fork the current process
```
[2020-11-06 13:36:37 +0100] [6124] [INFO] Starting gunicorn 20.0.4
[2020-11-06 13:36:37 +0100] [6124] [INFO] Listening at: http://0.0.0.0:8080 (6124)
[2020-11-06 13:36:37 +0100] [6124] [INFO] Using worker: threads
[2020-11-06 13:36:37 +0100] [6127] [INFO] Booting worker with pid: 6127
objc[6127]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[6127]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

To enable it I had to set this flag ([thanks to StackOverflow](https://stackoverflow.com/a/52230415/621058))
```
OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
```

I see that, when the functions-framework starts it says `Using worker: threads`. So can we use the "synchronous" gunicorn worker to avoid this? Or at least make it configurable as a `click` cli option?

Code I'm using
```python
import signal
import subprocess
import sys

process = subprocess.Popen(
    [
        'functions-framework',
        '--target', 'api',
        '--port', '8080',
    ],
    stdout=subprocess.PIPE,
)


def signal_handler(sig, frame):
    process.kill()
    process.wait()
    sys.exit(0)

signal.signal(signal.SIGINT, signal_handler)
signal.pause()
```

**Comment by di** [comment]
Hi @dinigo, sorry you're having problems, thanks for filing an issue.

Can you try adding the `--debug` flag?

```diff
process = subprocess.Popen(
    [
        'functions-framework',
        '--target', 'api',
        '--port', '8080',
+       '--debug',
    ],
    stdout=subprocess.PIPE,
)
```

**Comment by di** [comment]
You can also try what I've described in https://github.com/GoogleCloudPlatform/python-docs-samples/issues/4952 for a slightly simpler integration test.

**Comment by dinigo** [comment]
Just for reference, I tried the solution @di mentions in the link ([like so](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/4952#issuecomment-723575068)) and it works like charm.

I don't know if there should be changes in the documentation, or maybe launching the process itself is part of the test.

**Comment by di** [comment]
Glad to hear it @dinigo! Going to close this in favor of https://github.com/GoogleCloudPlatform/python-docs-samples/issues/4952 but thanks again for filing the issue.
